/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChampionsChampionNameRouteImport } from './routes/champions.$championName'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsChampionNameRoute = ChampionsChampionNameRouteImport.update({
  id: '/$championName',
  path: '/$championName',
  getParentRoute: () => ChampionsRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/champions/$championName': typeof ChampionsChampionNameRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/champions/$championName': typeof ChampionsChampionNameRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/champions/$championName': typeof ChampionsChampionNameRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champions'
    | '/focus'
    | '/goals'
    | '/insights'
    | '/matches'
    | '/overview'
    | '/progress'
    | '/roles'
    | '/settings'
    | '/champions/$championName'
    | '/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champions'
    | '/focus'
    | '/goals'
    | '/insights'
    | '/matches'
    | '/overview'
    | '/progress'
    | '/roles'
    | '/settings'
    | '/champions/$championName'
    | '/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/champions'
    | '/focus'
    | '/goals'
    | '/insights'
    | '/matches'
    | '/overview'
    | '/progress'
    | '/roles'
    | '/settings'
    | '/champions/$championName'
    | '/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsRoute: typeof ChampionsRouteWithChildren
  FocusRoute: typeof FocusRoute
  GoalsRoute: typeof GoalsRoute
  InsightsRoute: typeof InsightsRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  ProgressRoute: typeof ProgressRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/$championName': {
      id: '/champions/$championName'
      path: '/$championName'
      fullPath: '/champions/$championName'
      preLoaderRoute: typeof ChampionsChampionNameRouteImport
      parentRoute: typeof ChampionsRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
  }
}

interface ChampionsRouteChildren {
  ChampionsChampionNameRoute: typeof ChampionsChampionNameRoute
}

const ChampionsRouteChildren: ChampionsRouteChildren = {
  ChampionsChampionNameRoute: ChampionsChampionNameRoute,
}

const ChampionsRouteWithChildren = ChampionsRoute._addFileChildren(
  ChampionsRouteChildren,
)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsRoute: ChampionsRouteWithChildren,
  FocusRoute: FocusRoute,
  GoalsRoute: GoalsRoute,
  InsightsRoute: InsightsRoute,
  MatchesRoute: MatchesRouteWithChildren,
  OverviewRoute: OverviewRoute,
  ProgressRoute: ProgressRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
